'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://IPC2/", ConfigurationName:="ServiceReference1.NewWebService")>  _
    Public Interface NewWebService
        
        'CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://IPC2/NewWebService/helloRequest", ReplyAction:="http://IPC2/NewWebService/helloResponse")>  _
        Function hello(ByVal request As ServiceReference1.helloRequest) As ServiceReference1.helloResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://IPC2/NewWebService/helloRequest", ReplyAction:="http://IPC2/NewWebService/helloResponse")>  _
        Function helloAsync(ByVal request As ServiceReference1.helloRequest) As System.Threading.Tasks.Task(Of ServiceReference1.helloResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class helloRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="hello", [Namespace]:="http://IPC2/", Order:=0)>  _
        Public Body As ServiceReference1.helloRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.helloRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class helloRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class helloResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="helloResponse", [Namespace]:="http://IPC2/", Order:=0)>  _
        Public Body As ServiceReference1.helloResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.helloResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class helloResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface NewWebServiceChannel
        Inherits ServiceReference1.NewWebService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NewWebServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.NewWebService)
        Implements ServiceReference1.NewWebService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_NewWebService_hello(ByVal request As ServiceReference1.helloRequest) As ServiceReference1.helloResponse Implements ServiceReference1.NewWebService.hello
            Return MyBase.Channel.hello(request)
        End Function
        
        Public Function hello(ByVal name As String) As String
            Dim inValue As ServiceReference1.helloRequest = New ServiceReference1.helloRequest()
            inValue.Body = New ServiceReference1.helloRequestBody()
            inValue.Body.name = name
            Dim retVal As ServiceReference1.helloResponse = CType(Me,ServiceReference1.NewWebService).hello(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_NewWebService_helloAsync(ByVal request As ServiceReference1.helloRequest) As System.Threading.Tasks.Task(Of ServiceReference1.helloResponse) Implements ServiceReference1.NewWebService.helloAsync
            Return MyBase.Channel.helloAsync(request)
        End Function
        
        Public Function helloAsync(ByVal name As String) As System.Threading.Tasks.Task(Of ServiceReference1.helloResponse)
            Dim inValue As ServiceReference1.helloRequest = New ServiceReference1.helloRequest()
            inValue.Body = New ServiceReference1.helloRequestBody()
            inValue.Body.name = name
            Return CType(Me,ServiceReference1.NewWebService).helloAsync(inValue)
        End Function
    End Class
End Namespace
